# Prometheus設定 - Mobility Ops 360監視

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus自体の監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API監視
  - job_name: 'mobility-backend'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Node Exporter（システムメトリクス）
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # PostgreSQL監視
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis監視
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Traefik監視
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  # Custom Business Metrics
  - job_name: 'mobility-business-metrics'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/api/metrics/business'
    scrape_interval: 30s