name: Voice System Test

on:
  push:
    paths:
      - 'backend/src/**'
      - 'backend/api/**'
      - '.github/workflows/voice-test.yml'
  schedule:
    - cron: '0 */6 * * *'  # 6時間ごとに実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  voice-webhook-test:
    name: Test Voice Webhooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Test Voice Incoming Webhook
        run: |
          echo "🎤 Testing voice incoming webhook..."
          
          RESPONSE=$(curl -X POST https://mobility-ops-360-api.yukihamada.workers.dev/api/voice/incoming \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "From=%2B81901234567&To=%2B19592105018&CallSid=CAtest$(date +%s)" \
            -s)
          
          echo "Response:"
          echo "$RESPONSE" | xmllint --format - || echo "$RESPONSE"
          
          # Check if response contains expected TwiML
          if echo "$RESPONSE" | grep -q "<Response>"; then
            echo "✅ Voice incoming webhook test passed"
          else
            echo "❌ Voice incoming webhook test failed"
            exit 1
          fi

      - name: Test Speech Processing Webhook
        run: |
          echo "🗣️ Testing speech processing webhook..."
          
          RESPONSE=$(curl -X POST https://mobility-ops-360-api.yukihamada.workers.dev/api/voice/process-speech \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "SpeechResult=東京駅から渋谷駅まで&Confidence=0.95&CallSid=CAtest$(date +%s)" \
            -s)
          
          echo "Response:"
          echo "$RESPONSE" | xmllint --format - || echo "$RESPONSE"
          
          # Check if response contains the location
          if echo "$RESPONSE" | grep -q "東京駅から渋谷駅まで"; then
            echo "✅ Speech processing webhook test passed"
          else
            echo "❌ Speech processing webhook test failed"
            exit 1
          fi

      - name: Test Status Callback
        run: |
          echo "📊 Testing status callback webhook..."
          
          HTTP_CODE=$(curl -X POST https://mobility-ops-360-api.yukihamada.workers.dev/api/twilio/status \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "CallSid=CAtest$(date +%s)&CallStatus=completed&From=%2B81901234567&To=%2B19592105018" \
            -s -o /dev/null -w "%{http_code}")
          
          if [ "$HTTP_CODE" = "200" ]; then
            echo "✅ Status callback test passed (HTTP $HTTP_CODE)"
          else
            echo "❌ Status callback test failed (HTTP $HTTP_CODE)"
            exit 1
          fi

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Voice System Test Failed',
              body: `Voice webhook tests failed at ${new Date().toISOString()}
              
              Please check:
              - Twilio webhook configuration
              - API deployment status
              - Voice endpoint functionality
              
              [View workflow run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`
            };
            github.rest.issues.create(issue);